// <auto-generated />
namespace du_lich_bien_ba_dong.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class BaDong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BaDong));
        
        string IMigrationMetadata.Id
        {
            get { return "202606081521221_BaDong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
